# -*- coding: utf-8 -*-
"""Tugas Akhir V2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1BcNkF9SyuSl25YGqfoBT5Id3Hd1fWcHe

# Upload dan Validasi Dataset
"""

from google.colab import files
import pandas as pd

print("Upload dataset FINAL:")
uploaded = files.upload()

# Ambil nama file
filename = list(uploaded.keys())[0]

# Baca CSV dengan separator ;
df = pd.read_csv(filename, sep=';')

# Rapikan nama kolom
df.columns = df.columns.str.strip().str.lower()

# Rapikan isi label
df['label'] = (
    df['label']
    .astype(str)
    .str.strip()
    .str.lower()
)

# INFO
print("\n=== KOLOM DATASET ===")
print(df.columns)

print("\n=== INFORMASI DATASET ===")
print("Shape:", df.shape)

print("\nDistribusi Label:")
print(df['label'].value_counts())

print("\n5 Baris Pertama:")
display(df.head())

print(f"Total data: {len(df)}")
print(df['label'].value_counts())

"""# Visualisasi Distribusi dan Hubungan Antar Fitur"""

# CELL 2: Visualisasi Distribusi Fitur (Histogram 2x2 & Pairplot)
import matplotlib.pyplot as plt
import seaborn as sns

# ⚠️ OBAT PERMANEN: Paksa semua teks label di memori menjadi huruf kecil
df['label'] = df['label'].astype(str).str.lower()

FEATURES = ['interval_ms', 'latency_ms', 'jitter_ms', 'packet_rate']

# 1. Plot Distribusi Histogram (2x2 Grid)
fig, axes = plt.subplots(2, 2, figsize=(14, 10))
axes = axes.flatten()

for i, feature in enumerate(FEATURES):
    sns.histplot(data=df, x=feature, hue='label', bins=40, kde=True,
                 ax=axes[i], palette={'normal':'blue', 'dos':'red'}, alpha=0.6)
    axes[i].set_title(f'Distribusi {feature}')

plt.tight_layout()
plt.savefig('distribusi_4_fitur.png', dpi=300) # Resolusi tinggi untuk Skripsi
plt.show()

# 2. Plot Sebaran Multidimensi (Pairplot)
print("\nMembuat Scatter Matrix (Pairplot)... (Mungkin butuh waktu beberapa detik)")
pair_plot = sns.pairplot(df[FEATURES + ['label']], hue='label',
                         palette={'normal':'blue', 'dos':'red'},
                         plot_kws={'alpha':0.5, 's':15})
pair_plot.fig.suptitle("Scatter Matrix Korelasi Antar Fitur", y=1.02)
pair_plot.savefig('scatter_matrix_fitur.png', dpi=300)
plt.show()

print("✅ Plot tersimpan! (distribusi_4_fitur.png & scatter_matrix_fitur.png)")

"""# Prapemrosesan Data dan Pembagian Dataset

"""

# CELL 3: Data Preprocessing & Train-Test Split
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split

# Pisahkan Fitur (X) dan Target (y)
X = df[FEATURES]
y = df['label']

# Encode Label (normal = 0, dos = 1)
le = LabelEncoder()
y_encoded = le.fit_transform(y)

print("Fitur yang digunakan:", FEATURES)
print("Label mapping:", dict(zip(le.classes_, le.transform(le.classes_))))
print("Jumlah Missing Values:\n", X.isnull().sum())

# Split 80% Training, 20% Testing (Stratified agar rasio normal/dos seimbang)
X_train, X_test, y_train, y_test = train_test_split(
    X, y_encoded, test_size=0.2, random_state=42, stratify=y_encoded
)

print(f"\nDistribusi Data:")
print(f"Data Training : {len(X_train)} baris")
print(f"Data Testing  : {len(X_test)} baris")
print(f"Rasio DoS di Train : {y_train.mean():.2%}")
print(f"Rasio DoS di Test  : {y_test.mean():.2%}")

"""# Pelatihan dan Evaluasi Model Random Forest"""

# CELL 4: Random Forest (Supervised Learning)
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score

# Inisialisasi & Train Model
rf = RandomForestClassifier(n_estimators=100, max_depth=10, random_state=42)
rf.fit(X_train, y_train)

# Prediksi
y_pred_rf = rf.predict(X_test)
acc_rf = accuracy_score(y_test, y_pred_rf)

print(f"=== HASIL RANDOM FOREST ===")
print(f"Akurasi: {acc_rf*100:.2f}%\n")
print(classification_report(y_test, y_pred_rf, target_names=le.classes_))

# Confusion Matrix
cm_rf = confusion_matrix(y_test, y_pred_rf)
plt.figure(figsize=(6,4))
sns.heatmap(cm_rf, annot=True, fmt='d', cmap='Blues',
            xticklabels=le.classes_, yticklabels=le.classes_)
plt.title(f'Confusion Matrix RF — Akurasi: {acc_rf*100:.2f}%')
plt.ylabel('Aktual')
plt.xlabel('Prediksi')
plt.savefig('cm_random_forest.png', dpi=300)
plt.show()

"""# Pelatihan dan Evaluasi Model XGBoost"""

# CELL 5: XGBoost (Supervised Learning)
from xgboost import XGBClassifier
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score
import seaborn as sns
import matplotlib.pyplot as plt

# Inisialisasi & Train Model XGBoost
# Menggunakan hyperparameter tuning standar yang sangat bagus untuk data jaringan
xgb_model = XGBClassifier(
    n_estimators=150,        # Jumlah pohon
    max_depth=6,             # Kedalaman maksimal pohon
    learning_rate=0.1,       # Kecepatan belajar
    subsample=0.8,           # Mencegah overfitting
    colsample_bytree=0.8,    # Memilih fitur secara acak per pohon
    random_state=42,
    eval_metric='logloss'
)

# Berbeda dengan IF, XGBoost diajari menggunakan seluruh data training (Normal & DoS)
xgb_model.fit(X_train, y_train)

# Prediksi
y_pred_xgb = xgb_model.predict(X_test)

# Hitung Akurasi
acc_xgb = accuracy_score(y_test, y_pred_xgb)
print(f"=== HASIL XGBOOST ===")
print(f"Akurasi: {acc_xgb*100:.2f}%\n")
print(classification_report(y_test, y_pred_xgb, target_names=le.classes_))

# Confusion Matrix
cm_xgb = confusion_matrix(y_test, y_pred_xgb)
plt.figure(figsize=(6,4))
# Menggunakan warna Greens untuk membedakan dari Random Forest (Blues)
sns.heatmap(cm_xgb, annot=True, fmt='d', cmap='Greens',
            xticklabels=le.classes_, yticklabels=le.classes_)
plt.title(f'Confusion Matrix XGBoost — Akurasi: {acc_xgb*100:.2f}%')
plt.ylabel('Aktual')
plt.xlabel('Prediksi')
plt.savefig('cm_xgboost.png', dpi=300)
plt.show()

"""# Analisis Feature Importance"""

# CELL 6: Feature Importance (Fitur mana yang paling berpengaruh?)
import numpy as np

importance = rf.feature_importances_
indices = np.argsort(importance)[::-1]
sorted_features = [FEATURES[i] for i in indices]

plt.figure(figsize=(8,5))
sns.barplot(x=importance[indices], y=sorted_features, palette='viridis')
plt.title('Feature Importance', fontsize=14)
plt.xlabel('Tingkat Kepentingan (0.0 - 1.0)')
plt.ylabel('Fitur Jaringan')
plt.tight_layout()
plt.savefig('feature_importance.png', dpi=300)
plt.show()

print("Bobot masing-masing fitur:")
for i in indices:
    print(f"- {FEATURES[i]:15s}: {importance[i]:.4f}")

"""# Penyimpanan dan Ekspor Model Machine Learning"""

# CELL 7: Simpan Model & Download ke Laptop Anda
import joblib
from google.colab import files

# Simpan ke file
joblib.dump(rf, 'model_rf.pkl')
joblib.dump(xgb_model, 'model_xgb.pkl') # <-- Menyimpan XGBoost
joblib.dump(le, 'label_encoder.pkl')

print("✅ Model berhasil di-export ke format .pkl!")

# Download otomatis
files.download('model_rf.pkl')
files.download('model_xgb.pkl')
files.download('label_encoder.pkl')

"""# Simulasi Prediksi Menggunakan Model Tersimpan"""

# CELL 8: Simulasi Prediksi Model
import joblib
import pandas as pd

# Load model (simulasi jika dijalankan di Raspberry Pi)
model_rf  = joblib.load('model_rf.pkl')
model_xgb = joblib.load('model_xgb.pkl') # <-- Load XGBoost
encoder   = joblib.load('label_encoder.pkl')

# Pastikan urutan fitur sama persis dengan saat training
FEATURES = ['interval_ms', 'latency_ms', 'jitter_ms', 'packet_rate']

# Simulasi 1: Data Normal
dummy_normal = pd.DataFrame([{
    'interval_ms': 550, 'latency_ms': 20, 'jitter_ms': 2, 'packet_rate': 1.5
}])

# Simulasi 2: Data Serangan DoS
dummy_dos = pd.DataFrame([{
    'interval_ms': 1850, 'latency_ms': 210, 'jitter_ms': 140, 'packet_rate': 6.2
}])

# Prediksi Random Forest
rf_pred_normal = encoder.inverse_transform(model_rf.predict(dummy_normal[FEATURES]))[0]
rf_pred_dos    = encoder.inverse_transform(model_rf.predict(dummy_dos[FEATURES]))[0]

# Prediksi XGBoost (Logika sama dengan RF karena sama-sama Supervised)
xgb_pred_normal = encoder.inverse_transform(model_xgb.predict(dummy_normal[FEATURES]))[0]
xgb_pred_dos    = encoder.inverse_transform(model_xgb.predict(dummy_dos[FEATURES]))[0]

print("=== HASIL UJI COBA MODEL ===")
print("Data 1 (Seharusnya Normal):")
print(f" -> Tebakan Random Forest : {rf_pred_normal}")
print(f" -> Tebakan XGBoost       : {xgb_pred_normal}\n")

print("Data 2 (Seharusnya DoS):")
print(f" -> Tebakan Random Forest : {rf_pred_dos}")
print(f" -> Tebakan XGBoost       : {xgb_pred_dos}")